In [1]:
from docx import Document
from transformers import AutoTokenizer

# === Шаг 1. Извлечь жирные сущности и текст ===
def extract_bold_entities(docx_path):
    doc = Document(docx_path)
    sentences = []
    bold_entities = set()

    for para in doc.paragraphs:
        sentence = ""
        for run in para.runs:
            text = run.text
            if run.bold and text.strip():
                bold_entities.add(text.strip())
            sentence += text
        if sentence.strip():
            sentences.append(sentence.strip())
    return sentences, bold_entities

# === Шаг 2. Загрузить файл с сущностями и категориями ===
def load_entity_labels(file_path):
    entity_to_label = {}
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            parts = line.strip().rsplit(' ', 1)
            if len(parts) == 2:
                entity, label = parts
                entity_to_label[entity.strip()] = label.strip()
    return entity_to_label

# === Шаг 3. Связать жирные сущности с категориями ===
def match_entities_with_labels(bold_entities, entity_to_label):
    matched = {}
    unmatched = []

    for entity in bold_entities:
        if entity in entity_to_label:
            matched[entity] = entity_to_label[entity]
        else:
            unmatched.append(entity)
    return matched, unmatched

# === Шаг 4. Основной код ===
if __name__ == "__main__":
    docx_path = "texts/entities.docx"
    labels_path = "texts/entities_metka.txt"
    # Загружаем
    sentences, bold_entities = extract_bold_entities(docx_path)
    entity_to_label = load_entity_labels(labels_path)
    matched, unmatched = match_entities_with_labels(bold_entities, entity_to_label)

    # Показываем результат
    print("\n📌 Найденные сущности с категориями:")
    for entity, label in matched.items():
        print(f"  {entity} → {label}")

    if unmatched:
        print("\n Сущности, для которых НЕ найдены категории:")
        for entity in unmatched:
            print(f"  {entity}")

    print("\n📄 Всего предложений:", len(sentences))
    print("Пример предложений:")
    for i, s in enumerate(sentences[:5]):
        print(f"  {i+1}: {s}")

/home/nika/Documents/Code/NER/.venv/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

📌 Найденные сущности с категориями:
  Билибиным → PER
  Мюрата → PER
  de Berlin → GPE
  венский мост → FAC
  Мортье → PER
  Владимира с бантом → VEH
  Брюнн → GPE
  венско-цнаймскую → FAC
  ваш Петр → PER
  Кремса → GPE
  Суворове → PER
  деревне Зальценек → GPE
  Долгоруков → PER
  Андрей Болконский → PER
  Павлоградского гусарского полков → ORG
  der Donau → GPE
  эрцгерцог Фердинанд → PER
  Дунай → LOC
  Вена → GPE
  Александра Первого → PER
  Болконский → PER
  Несвицкого → PER
  Грунт → GPE
  Иван Лукич → PER
  pont de Vienne → FAC
  Браунау → GPE
  Цнайм → GPE
  императору Францу → PER
  Матвевны → VEH
  Государь → PER
  Антонов → PER
  d’Ulm → GPE
  Бандарчука → PER
  Гольдбахом → LOC
  Вене → GPE
  Андрею → PER
  pont de Thabor → FAC
  Экономовым → PER
  Г’остов → PER
  Репнина → PER
  фрейлейн Матильду → PER
  императора Франца → PER
  Мюрат → PER
  de Vienne → GPE
  Мюрату → PER
  князем Ипполитом Курагиным → PER
  Остралиц → GPE
  Дунае → LOC
  Le prince d’Auersperg → PER
  de Brünn → GPE
  Денисовым → PER
  Ростовым → PER
  король Франц → PER
  Франца → PER
  Ипполиту → PER
  Русь → GPE
  Ростову → PER
  Лондон → GPE
  Париже → GPE
  Франц → PER
  Ланжерона → PER
  Брюнну → GPE
  князем Багратионом → PER
  Ольмюцкий → GPE
  Богемских гор → LOC
  de l’Angleterre → GPE
  Линце → GPE
  Маком → PER
  Суворова → PER
  Медведев → PER
  Тимохиным → PER
  России → GPE
  Подольский → ORG
  князь Ауэрсперг → PER
  Долохову → PER
  Аустерлицкого сражения → VEH
  Бандарчук → PER
  Энса → LOC
  Подольский егерский → ORG
  Шмитом → PER
  Князь Андрей → PER
  Долгорукова → PER
  Бергов → PER
  Праценским → LOC
  павлоградцев → ORG
  de Thabor → FAC
  Сухтелена → PER
  de Bilibine → PER
  Измайловском полку → ORG
  Дохтуров → PER
  ульмскому → GPE
  Голлабруне → GPE
  графа Ностица → GPE
  Бедуин → VEH
  Князь Багратион → PER
  Кремс → GPE
  Жеркова → PER
  Толстой → PER
  Вейрогеру → PER
  Билибину → PER
  Тит → PER
  Лаврушку → PER
  Вейротером → PER
  Васьки Денисова → PER
  Працена → GPE
  Бориса → PER
  Вейротера → PER
  Шенграбеном → VEH
  Геную → GPE
  Oestreicher → PER
  Никитенко → PER
  Александре → PER
  Москва → GPE
  Працем → GPE
  Бонапарте → PER
  Богданычем → PER
  Дунаем → LOC
  Ламбахе → GPE
  Бунапарт → PER
  Шенграбен → GPE
  Штраух → PER
  Гостиерадек → GPE
  Новосильцева → PER
  Денисов → PER
  Репнин → PER
  Болконскому → PER
  Наполеону → PER
  Несвицким → PER
  князя Багратиона → PER
  Киевский гренадерский → ORG
  Берг → PER
  Богемские → LOC
  Гусарский Павлоградский полк → ORG
  с орденом Марии-Терезии → VEH
  Ауэрсперг → PER
  Чарторижский → PER
  князь Ипполит → PER
  Тюрасе → GPE
  Праценской → LOC
  князь Багратион → PER
  Лаврушка → PER
  Прац → GPE
  Толь → PER
  Гостиерадеке → GPE
  Буксгевденом → PER
  Ильи Андреича → PER
  Маку → PER
  Тимохин → PER
  Польше → GPE
  Жерковым → PER
  Праценской горе → LOC
  Thuerassa-Walde → LOC
  Фердинанд → PER
  Аустерлицкому сражению → VEH
  Италии → GPE
  Трауне → LOC
  Козловский → PER
  Ланна → PER
  Борисом → PER
  Сидоров → PER
  Фердинанда → PER
  Амштетене → GPE
  Буонапарте → PER
  Курагина → PER
  Тушина → PER
  Ларрей → PER
  апшеронцев → ORG
  Кремсе → GPE
  Адам Чарторижский → PER
  Тимохина → PER
  Болконского → PER
  Багратионовых → PER
  Чарторижскому → PER
  Гурьева → PER
  Бедуину → VEH
  Цнаймом → GPE
  Васька Денисов → PER
  князю Андрею → PER
  Новгородского → PER
  Теляниным → PER
  Бедуина → PER
  Милорадовича → PER
  Марией-Терезией большого креста → VEH
  Souvara → PER
  Киевский полк → ORG
  Наполеонова → PER
  Кутузовскою → PER
  Грунте → GPE
  Несвицкий → PER
  Друбецким → PER
  Голлабруну → GPE
  Зальценека → GPE
  Денисова → PER
  Инне → LOC
  Князю Андрею → PER
  Денисову → PER
  Пруссия → GPE
  Александр → PER
  Долгоруковым → PER
  Билибина → PER
  Павлоградского полка → ORG
  Жерков → PER
  Таборский мост → FAC
  Андреем → GPE
  Матвевна → VEH
  Ulm → GPE
  Лысых Горах → LOC
  кремско-цнаймской дороги → FAC
  Иван Митрич → PER
  князь Ауэрсперг фон Маутерн → PER
  Долохов → PER
  Шенграбена → GPE
  эрцгерцогства Австрийского → GPE
  император Франц → PER
  Шмита → PER
  Наполеон → PER
  Наполеона → PER
  Пржебышевского → PER
  Шлапаниц → GPE
  Царицыном Лугу → FAC
  павлоградскими → ORG
  Багратиона → PER
  Брюнне → GPE
  Сокольница → GPE
  Гурьев → PER
  Волконский → PER
  Buonaparte → PER
  de Dürenstein → GPE
  Ланжероном → PER
  Брюнна → GPE
  Кутузове → PER
  Кутузовым → PER
  Козловского → GPE
  Александра → PER
  l’Autriche → GPE
  Schoenbrunn → GPE
  Лемарруа (Lemarrois) → PER
  Грачик → PER
  Марье → PER
  Голлабрун → GPE
  Курагиным → PER
  Сухтелен → PER
  Энс → LOC
  Тверской → FAC
  Телянину → PER
  Наполеоном → PER
  Россию → GPE
  Вася → PER
  генерал-адъютанта Винценгероде → PER
  Маркова → PER
  Бонапарта → PER
  Мельке → GPE
  Телянин → PER
  Шенбрунне → GPE
  à Ulm → GPE
  Жучка → VEH
  Билибин → PER
  Австрия → GPE
  Францу → PER
  Аустерлицком → LOC
  Брунове → GPE
  Новосильцев → PER
  Дунаю → LOC
  эрцгерцога Фердинанда → PER
  Федотов → PER
  Козловскому → PER
  Князь Ауэрсперг → PER
  Кутузову → PER
  Дохтурова → PER
  die Kaiserlich-Russische Armee → ORG
  Mack → PER
  Турции → GPE
  Экономову → PER
  Цнайма → GPE
  Винценгероде → PER
  Бедуине → VEH
  Николая → PER
  Аркольского моста → FAC
  Строганов → PER
  Францией → GPE
  Телянина → PER
  Аугеста → GPE
  Федченку → PER
  Мортъе → PER
  князь Андрей → PER
  Несвицкому → PER
  Бонапарту → PER
  Мака → PER
  Император Франц → PER
  Ауэрсперга → PER
  Дюренштейне → GPE
  Проценских → LOC
  Кутузова → PER
  Бедуином → VEH
  Вены → GPE
  Ростова → PER
  павлоградцам → ORG
  штабс-капитана Тушина → PER
  Ланжерон → PER
  Пржебышевский → PER
  Грачику → PER
  Измаилом → GPE
  Працу → GPE
  Тулон → PER
  Лаврушке → PER
  капитан Тушин → PER
  Карл Богданович Шуберт → PER
  Эссена → PER
  Kobelnitz → GPE
  du Mack → PER
  Марковым → PER
  Михайло Митрич → PER
  цнаймской дороге → FAC
  Мак → PER
  Голлабрунне → GPE
  орденом Марии-Терезии 3-й степени → VEH
  Апшеронского → ORG
  Миг’онов → PER
  Ольмюце → GPE
  Марсовом Поле → FAC
  Кремсу → GPE
  Эрцгерцог Карл → PER
  Кирстену → PER
  Богемии → LOC
  Wimpfen → PER
  Тушин → PER
  Петербурге → GPE
  Дуная → LOC
  Князь Ипполит → PER
  Ауэрспергом → PER
  Кремсом → GPE
  Франции → GPE
  Богемские горы → LOC
  Вишау → GPE
  Грачике → PER
  Ростов → PER
  die Donau → GPE
  Милорадович → PER
  Сокольниц → GPE
  Цнайме → GPE
  Толстому → PER
  Bellowitz → GPE
  эрцгерцог Карл → PER
  князя Андрея → PER
  Багратионова → PER
  Николай Ростов → PER
  Кутузов → PER
  Тушиным → PER
  Гунтерсдорф → GPE
  Толю → PER
  Багратиону → PER
  Бельяр → PER
  Bonaparte → PER
  Шмит → PER
  Ипполит → PER
  Sokolnitz → GPE
  граф Лихтенфельс → PER
  Kaiser Alexander → PER
  Ольмюца → GPE
  Каменскиим-отцом → PER
  Голлабруна → GPE
  Праца → GPE
  Марьею → PER
  Илью Ивановича → PER
  Богданычу → PER
  Аракчеев → PER
  Андрея → PER
  Ольмюцком → LOC
  Михаил Ларионович → PER
  Суворов → PER
  Берга → PER
  императора Александра → PER
  Англии → GPE
  Буонапарту → PER
  Князь Андрей Болконский → PER
  Грунта → GPE
  Петров → PER
  Тулона → PER
  Тушину → PER
  Вену → GPE
  Быкова → PER
  Вейротер → PER
  Андрей → PER
  Австрии → GPE
  Жеркову → PER
  Энском мосту → FAC
  Грачика → PER
  Le prince Murat → PER
  Праценских → LOC
  Ольмюц → GPE
  генерал Мак → PER
  Илья-кучер → PER
  Ауэрспергу → PER
  Савари → PER
  Дюренштейна → GPE
  den Lech → GPE
  Долгорукову → PER
  Ланн → PER
  Кобельница → GPE
  Буксгевден → PER
  эрцгерцога Карла → PER
  Ланну → PER
  Праценские → LOC
  Уварова → PER
  Миронов → PER
  Вилье → PER
  Матвевну → VEH
  Кирстен → PER
  Борис → PER
  Schlapanitz → GPE
  граф Ностиц → PER
  Багратионом → PER
  Борису → PER
  Николай → PER
  Шварценберга → PER
  Ульмом → GPE
  Марков → PER
  Долохова → PER
  кремско-цнаймской → FAC
  Лавг’ушка → PER
  Михаил Иларионович → PER
  Ульма → GPE
  Лаврушки → PER
  павлоградскому → ORG
  Цнайму → GPE
  Богданыч → PER
  Шенбрунна → GPE
  Титом → PER
  Шлапанице → GPE
  Бондаренко → PER
  huzards de Pavlograd → ORG
  Аустерлицкое → VEH
  Зикин → PER
  князем Андреем → PER
  Ваську Денисова → PER
  Матвевной → VEH
  Бонапарт → PER
  Au prince Murât → PER
  Апшеронский → ORG
  Копенгагене → GPE
  Энский мост → FAC
  Ларрея → PER
  Багратион → PER
  Вейротеру → PER

 Сущности, для которых НЕ найдены категории:
  Эцельс-дорфа
  Тимохину
  Федешоу
  Долохове
  высотах
  князь Андр
  Христос с тобой
  Амели
  князь
  Буопапарте
  Бонапарта,
  de Hohenloe
  Латш
  de Lichtenstein
  эрцгерцога
  императору Францу,
  Азовского и Подольского пехотных
  de Langeron
  кавалерийской дивизии под именем Васьки Денисова
  Наташи
  бога благодарить
  с нами бог, а бог с вами
  Prsch... prsch
  Господи боже
  Бог с тобой
  князя Андрея.
  Аугесту
  Бахусу
  Шмите
  Ах, мой Бог!
  ради Христа
  Игнатьич
  Сони
  ольмюцком
  князь Андрей.
  кутузовская
  Бунапартом
  Прохор
  генерале
  Подновинское

📄 Всего предложений: 49
Пример предложений:
  1: Том 1. Часть 2.
Глава I

В октябре 1805 года русские войска занимали села и города эрцгерцогства Австрийского, и еще новые полки приходили из России, и, отягощая постоем жителей, располагались у крепости Браунау. В Браунау была главная квартира главнокомандующего Кутузова.

11-го октября 1805 года один из только что пришедших к Браунау пехотных полков, ожидая смотра главнокомандующего, стоял в полумиле от города. Несмотря на нерусскую местность и обстановку: фруктовые сады, каменные ограды, черепичные крыши, горы, видневшиеся вдали, — на нерусский народ, с любопытством смотревший на солдат, — полк имел точно такой же вид, какой имел всякий русский полк, готовившийся к смотру где-нибудь в середине России.

С вечера, на последнем переходе, был получен приказ, что главнокомандующий будет смотреть полк на походе. Хотя слова приказа и показались неясны полковому командиру и возник вопрос, как разуметь слова приказа: в походной форме или нет? — в совете батальонных командиров было решено представить полк в парадной форме на том основании, что всегда лучше перекланяться, чем недокланяться. И солдаты, после тридцативерстного перехода, не смыкали глаз, всю ночь чинились, чистились: адъютанты и ротные рассчитывали, отчисляли; и к утру полк, вместо растянутой беспорядочной толпы, какою он был накануне на последнем переходе, представлял стройную массу двух тысяч людей, из которых каждый знал свое место, свое дело, из которых на каждом каждая пуговка и ремешок были на своем месте и блестели чистотой. Не только наружное было исправно, но ежели бы угодно было главнокомандующему заглянуть под мундиры, то на каждом он увидел бы одинаково чистую рубаху и в каждом ранце нашел бы узаконенное число вещей, «шильце и мыльце», как говорят солдаты. Было только одно обстоятельство, насчет которого никто не мог быть спокоен. Это была обувь. Больше чем у половины людей сапоги были разбиты. Но недостаток этот происходил не от вины полкового командира, так как, несмотря на неоднократные требования, ему не был отпущен товар от австрийского ведомства, а полк прошел тысячу верст.

Полковой командир был пожилой, сангвинический, с седеющими бровями и бакенбардами генерал, плотный и широкий больше от груди к спине, чем от одного плеча к другому. На нем был новый, с иголочки, со слежавшимися складками, мундир и густые золотые эполеты, которые как будто не книзу, а кверху поднимали его тучные плечи. Полковой командир имел вид человека, счастливо совершающего одно из самых торжественных дел жизни. Он похаживал перед фронтом и, похаживая, подрагивал на каждом шагу, слегка изгибаясь спиною. Видно было, что полковой командир любуется своим полком, счастлив им и что все его силы душевные заняты только полком; но несмотря на то, его подрагивающая походка как будто говорила, что, кроме военных интересов, в душе его немалое место занимают и интересы общественного быта и женский пол.

— Ну, батюшка Михайло Митрич, — обратился он к одному батальонному командиру (батальонный командир, улыбаясь, подался вперед; видно было, что они были счастливы), — досталось на орехи нынче ночью. Однако, кажется, ничего, полк не из дурных... А?

Батальонный командир понял веселую иронию и засмеялся.

— И на Царицыном Лугу с поля бы не прогнали.

— Что? — сказал командир.

В это время по дороге из города, по которой были расставлены махальные, показались два верховые. Это были адъютант и казак, ехавший сзади. Адъютант был прислан из главного штаба подтвердить полковому командиру то, что было сказано неясно во вчерашнем приказе, а именно то, что главнокомандующий желал видеть полк совершенно в том положении, в котором он шел — в шинелях, в чехлах и без всяких приготовлений.

К Кутузову накануне прибыл член гофкригсрата из Вены, с предложениями и требованиями идти как можно скорее на соединение с армией эрцгерцога Фердинанда и Мака, и Кутузов, не считавший выгодным это соединение, в числе прочих доказательств в пользу своего мнения намеревался показать австрийскому генералу то печальное положение, в котором приходили войска из России. С этой целью он и хотел выехать навстречу полку, так что, чем хуже было бы положение полка, тем приятнее было бы это главнокомандующему. Хотя адъютант и не знал этих подробностей, однако он передал полковому командиру непременное требование главнокомандующего, чтобы люди были в шинелях и чехлах, и что в противном случае главнокомандующий будет недоволен.

Выслушав эти слова, полковой командир опустил голову, молча вздернул плечами и сангвиническим жестом развел руки.

— Наделали дела! — проговорил он. — Вот я вам говорил же, Михайло Митрич, что на походе, так в шинелях, — обратился он с упреком к батальонному командиру. — Ах, мой Бог! — прибавил он и решительно выступил вперед. — Господа ротные командиры! — крикнул он голосом, привычным к команде. — Фельдфебелей!.. Скоро ли пожалуют? — обратился он к приехавшему адъютанту с выражением почтительной учтивости, видимо, относившейся к лицу, про которое он говорил.

— Через час, я думаю.

— Успеем переодеть?

— Не знаю, генерал...

Полковой командир, сам подойдя к рядам, распорядился переодеванием опять в шинели. Ротные командиры разбежались по ротам, фельдфебели засуетились (шинели были не совсем исправны), и в то же мгновение заколыхались, растянулись и говором загудели прежде правильные, молчаливые четвероугольники. Со всех сторон отбегали и подбегали солдаты, подкидывали сзади плечом, через голову перетаскивали ранцы, снимали шинели и, высоко поднимая руки, втягивали их в рукава.

Через полчаса все опять пришло в прежний порядок, только четвероугольники сделались серыми из черных. Полковой командир опять подрагивающей походкой вышел вперед полка и издалека оглядел его.

— Это что еще? это что? — прокричал он, останавливаясь. — Командира третьей роты!..

— Командир третьей роты к генералу! командира к генералу, третьей роты к командиру!.. — послышались голоса по рядам и адъютант побежал отыскивать замешкавшегося офицера.

Когда звуки усердных голосов, перевирая, крича уже «генерала в третью роту», дошли по назначению, требуемый офицер показался из-за роты и, хотя человек уже пожилой и не имевший привычки бегать, неловко цепляясь носками, рысью направился к генералу. Лицо капитана выражало беспокойство школьника, которому велят сказать не выученный им урок. На красном (очевидно, от невоздержания) лице выступали пятна, и рот не находил положения. Полковой командир с ног до головы осматривал капитана, в то время как он, запыхавшись, подходил, по мере приближения сдерживая шаг.

— Вы скоро людей в сарафаны нарядите? Это что? — крикнул полковой командир, выдвигая нижнюю челюсть и указывая в рядах 3-й роты на солдата в шинели цвета фабричного сукна, отличавшегося от других шинелей. — Сами где находились? Ожидается главнокомандующий, а вы отходите от своего места? А?.. Я вас научу, как на смотр людей в казакины одевать!.. А?

Ротный командир, не спуская глаз с начальника, все больше и больше прижимал свои два пальца к козырьку, как будто в одном этом прижимании он видел теперь свое спасение.

— Ну, что ж вы молчите? Кто у вас там в венгерца наряжен? — строго шутил полковой командир.

— Ваше превосходительство...

— Ну, что «ваше превосходительство?» Ваше превосходительство! Ваше превосходительство! А что ваше превосходительство — никому не известно.

— Ваше превосходительство, это Долохов, разжалованный... — сказал тихо капитан.

— Что, он в фельдмаршалы разжалован, что ли, или в солдаты? А солдат, так должен быть одет, как все, по форме.

— Ваше превосходительство, вы сами разрешили ему походом.

— Разрешил? Разрешил? Вот вы всегда так, молодые люди, — сказал полковой командир, остывая несколько. — Разрешил? Вам что-нибудь скажешь, а вы и... — Полковой командир помолчал. — Вам что-нибудь скажешь, а вы и... Что? — сказал он, снова раздражаясь. — Извольте одеть людей прилично...

И полковой командир, оглянувшись на адъютанта, своею вздрагивающею походкой направился к полку. Видно было, что его раздражение ему самому не понравилось и что он, пройдясь по полку, хотел найти еще предлог своему гневу. Оборвав одного офицера за невычищенный знак, другого за неправильность ряда, он подошел к 3-й роте.

— Ка-а-ак стоишь? Где нога? Нога где? — закричал полковой командир с выражением страдания в голосе, еще человек за пять не доходя до Долохова, одетого в синеватую шинель.

Долохов медленно выпрямил согнутую ногу и прямо, своим светлым и наглым взглядом, посмотрел в лицо генерала.

— Зачем синяя шинель? Долой!.. Фельдфебель! Переодеть его... дря... — Он не успел договорить.

— Генерал, я обязан исполнить приказания, но не обязан переносить... — поспешно сказал Долохов.

— Во фронте не разговаривать!.. Не разговаривать, не разговаривать!..

— Не обязан переносить оскорбления, — громко, звучно договорил Долохов.

Глаза генерала и солдата встретились. Генерал замолчал, сердито оттягивая книзу тугой шарф.

— Извольте переодеться, прошу вас, — сказал он, отходя.
  2: Глава II

— Едет! — закричал в это время махальный.

Полковой командир, покраснев, подбежал к лошади, дрожащими руками взялся за стремя, перекинул тело, оправился, вынул шпагу и с счастливым, решительным лицом, набок раскрыв рот, приготовился крикнуть. Полк встрепенулся, как оправляющаяся птица, и замер.

— Смир-р-р-на! — закричал полковой командир потрясающим душу голосом, радостным для себя, строгим в отношении к полку и приветливым в отношении к подъезжающему начальнику.

По широкой, обсаженной деревьями, большой бесшоссейной дороге, слегка погромыхивая рессорами, шибкою рысью ехала высокая голубая венская коляска цугом. За коляской скакали свита и конвой кроатов. Подле Кутузова сидел австрийский генерал в странном, среди черных русских, белом мундире. Коляска остановилась у полка. Кутузов и австрийский генерал о чем-то тихо говорили, и Кутузов слегка улыбнулся, в то время как, тяжело ступая, он опускал ногу с подножки, точно как будто и не было этих двух тысяч людей, которые не дыша смотрели на него и на полкового командира.

Раздался крик команды, опять полк звеня дрогнул, сделав на караул. В мертвой тишине послышался слабый голос главнокомандующего. Полк рявкнул: «Здравья желаем, ваше го-го-го-ство!» И опять все замерло. Сначала Кутузов стоял на одном месте, пока полк двигался; потом Кутузов рядом с белым генералом, пешком, сопутствуемый свитою, стал ходить по рядам.


In [2]:
import os
import random
import re
from pathlib import Path
from docx import Document
from transformers import AutoTokenizer

# === Пути ===
docx_path = "texts/entities.docx"
labels_path = "texts/entities_metka.txt"
output_dir = Path("rubert.ipynb/datasets")
output_dir.mkdir(parents=True, exist_ok=True)

# === Шаг 1: Извлечение жирных сущностей и текста ===
def extract_bold_entities(docx_path):
    doc = Document(docx_path)
    sentences = []
    bold_entities = set()

    for para in doc.paragraphs:
        sentence = ""
        for run in para.runs:
            text = run.text
            if run.bold and text.strip():
                bold_entities.add(text.strip())
            sentence += text

        # Разбиваем абзац на предложения
        if sentence.strip():
            split_sentences = re.split(r'(?<=[.!?])\s+', sentence.strip())
            sentences.extend(split_sentences)

    return sentences, bold_entities

# === Шаг 2: Загрузка категорий сущностей ===
def load_entity_labels(file_path):
    entity_to_label = {}
    with open(file_path, 'r', encoding='utf-8') as f:
        for line in f:
            parts = line.strip().rsplit(' ', 1)
            if len(parts) == 2:
                entity, label = parts
                entity_to_label[entity.strip()] = label.strip()
    return entity_to_label

# === Шаг 3: BIO-разметка с учетом offset-ов ===
def tokenize_and_tag_sentences(sentences, matched_entities, tokenizer):
    data = []
    for sentence in sentences:
        encoding = tokenizer(
            sentence,
            return_offsets_mapping=True,
            truncation=True,
            padding="max_length",
            max_length=512,
            return_tensors=None,
        )

        input_ids = encoding["input_ids"]
        offsets = encoding["offset_mapping"]
        tokens = tokenizer.convert_ids_to_tokens(input_ids)
        labels = ["O"] * len(tokens)

        for entity, tag in matched_entities.items():
            if not entity.strip():
                continue
            start_idx = 0
            while True:
                start = sentence.find(entity, start_idx)
                if start == -1:
                    break
                end = start + len(entity)

                for i, (token_start, token_end) in enumerate(offsets):
                    if token_start is None or token_end is None:
                        continue
                    if token_start >= start and token_end <= end:
                        if labels[i] == "O":
                            labels[i] = f"B-{tag}" if token_start == start else f"I-{tag}"
                start_idx = end

        data.append((tokens, labels))
    return data

# === Поддержка: объединение субтокенов ===
def merge_subword_tokens(tokens, labels):
    merged_tokens = []
    merged_labels = []

    for token, label in zip(tokens, labels):
        if token.startswith("##") and merged_tokens:
            merged_tokens[-1] += token[2:]
        else:
            merged_tokens.append(token)
            merged_labels.append(label)
    return merged_tokens, merged_labels

# === Шаг 4: Сохранение в .txt ===
def save_to_txt(data, path, tokenizer):
    with open(path, "w", encoding="utf-8") as f:
        for tokens, labels in data:
            tokens, labels = merge_subword_tokens(tokens, labels)
            for t, l in zip(tokens, labels):
                if t in tokenizer.all_special_tokens:
                    continue
                f.write(f"{t} {l}\n")
            f.write("\n")  # Пустая строка между предложениями

# === Шаг 5: Основной запуск ===
if __name__ == "__main__":
    # Загрузка текста и сущностей
    sentences, bold_entities = extract_bold_entities(docx_path)
    entity_to_label = load_entity_labels(labels_path)

    matched = {e: entity_to_label[e] for e in bold_entities if e in entity_to_label}
    tokenizer = AutoTokenizer.from_pretrained("DeepPavlov/rubert-base-cased")

    print(f"📄 Найдено предложений: {len(sentences)}")
    print(f"🏷  Жирных сущностей с категорией: {len(matched)}")

    # BIO-разметка
    data = tokenize_and_tag_sentences(sentences, matched, tokenizer)

    # Перемешиваем и делим
    random.seed(42)
    random.shuffle(data)
    n = len(data)
    train_data = data[:int(n * 0.7)]
    val_data = data[int(n * 0.7):int(n * 0.85)]
    test_data = data[int(n * 0.85):]

    # Сохраняем
    save_to_txt(train_data, output_dir / "train.txt", tokenizer)
    save_to_txt(val_data, output_dir / "val.txt", tokenizer)
    save_to_txt(test_data, output_dir / "test.txt", tokenizer)

    print("\n✅ Готово! BIO-разметка сохранена в:")
    print(f" - {output_dir / 'train.txt'}")
    print(f" - {output_dir / 'val.txt'}")
    print(f" - {output_dir / 'test.txt'}")

📄 Найдено предложений: 3114
🏷  Жирных сущностей с категорией: 444

✅ Готово! BIO-разметка сохранена в:
 - rubert.ipynb/datasets/train.txt
 - rubert.ipynb/datasets/val.txt
 - rubert.ipynb/datasets/test.txt

In [3]:
import os
import numpy as np
from pathlib import Path
from transformers import AutoTokenizer, AutoModelForTokenClassification, TrainingArguments, Trainer, DataCollatorForTokenClassification
from datasets import DatasetDict, Dataset
from sklearn.metrics import classification_report
from seqeval.metrics import f1_score, classification_report as seqeval_classification_report

# === Пути ===
data_dir = Path("rubert.ipynb/datasets")
model_checkpoint = "DeepPavlov/rubert-base-cased"
label_list = ['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC', 'B-GPE', 'I-GPE', 'B-FAC', 'I-FAC', 'B-VEH', 'I-VEH']
label2id = {label: i for i, label in enumerate(label_list)}
id2label = {i: label for label, i in label2id.items()}

# === Загрузка BIO-данных из файлов ===
def load_bio_dataset(data_dir):
    def read_file(file_path):
        tokens = []
        labels = []
        with open(file_path, encoding='utf-8') as f:
            tok_seq = []
            lab_seq = []
            for line in f:
                line = line.strip()
                if not line:
                    if tok_seq:
                        tokens.append(tok_seq)
                        labels.append(lab_seq)
                        tok_seq, lab_seq = [], []
                else:
                    token, label = line.split()
                    tok_seq.append(token)
                    lab_seq.append(label)
        return {"tokens": tokens, "ner_tags": labels}

    return DatasetDict({
        "train": Dataset.from_dict(read_file(data_dir / "train.txt")),
        "validation": Dataset.from_dict(read_file(data_dir / "val.txt")),
        "test": Dataset.from_dict(read_file(data_dir / "test.txt")),
    })

# === Токенизатор ===
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

# === Преобразуем строки меток в ID ===
def encode_labels(example):
    tokens = example["tokens"]
    labels = example["ner_tags"]
    tokenized = tokenizer(tokens, is_split_into_words=True, truncation=True)
    word_ids = tokenized.word_ids()
    aligned_labels = []
    previous_word_idx = None
    for word_idx in word_ids:
        if word_idx is None:
            aligned_labels.append(-100)
        elif word_idx != previous_word_idx:
            aligned_labels.append(label2id[labels[word_idx]])
        else:
            # В случае субтокена
            label = labels[word_idx]
            if label.startswith("B-"):
                label = label.replace("B-", "I-")
            aligned_labels.append(label2id[label])
        previous_word_idx = word_idx
    tokenized["labels"] = aligned_labels
    return tokenized

# === Загружаем данные ===
dataset = load_bio_dataset(data_dir)
encoded_dataset = dataset.map(encode_labels, batched=False)

# === Модель ===
model = AutoModelForTokenClassification.from_pretrained(
    model_checkpoint,
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)

# === Аргументы тренировки ===
training_args = TrainingArguments(
    output_dir="./rubert-ner",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=4,
    weight_decay=0.01,
    save_total_limit=2,
    logging_dir="./logs",
    logging_steps=50,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
)

# === Вычисление метрик ===
def compute_metrics(eval_preds):
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)

    true_labels = []
    true_predictions = []

    for pred, lab in zip(predictions, labels):
        cur_labels = []
        cur_preds = []
        for p, l in zip(pred, lab):
            if l != -100:
                cur_labels.append(id2label[l])
                cur_preds.append(id2label[p])
        true_labels.append(cur_labels)
        true_predictions.append(cur_preds)

    f1 = f1_score(true_labels, true_predictions)
    print(seqeval_classification_report(true_labels, true_predictions))
    return {"f1": f1}

# === Обучение ===
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset["validation"],
    tokenizer=tokenizer,
    data_collator=DataCollatorForTokenClassification(tokenizer),
    compute_metrics=compute_metrics,
)

trainer.train()
trainer.save_model("./rubert-ner/final")
tokenizer.save_pretrained("./rubert-ner/final")

2025-04-14 16:27:59.208447: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-04-14 16:27:59.215427: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-14 16:27:59.264938: I external/local_xla/xla/tsl/cuda/cudart_stub.cc:32] Could not find cuda drivers on your machine, GPU will not be used.
2025-04-14 16:27:59.312671: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:467] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1744637279.353197    7305 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1744637279.364996    7305 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
W0000 00:00:1744637279.447664    7305 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744637279.447684    7305 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744637279.447685    7305 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
W0000 00:00:1744637279.447686    7305 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
2025-04-14 16:27:59.458087: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Map:   0%|          | 0/2179 [00:00<?, ? examples/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Map: 100%|██████████| 2179/2179 [00:00<00:00, 6644.30 examples/s]
Map: 100%|██████████| 467/467 [00:00<00:00, 6610.06 examples/s]
Map: 100%|██████████| 468/468 [00:00<00:00, 6906.20 examples/s]
Some weights of BertForTokenClassification were not initialized from the model checkpoint at DeepPavlov/rubert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/nika/Documents/Code/NER/.venv/lib/python3.10/site-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_7305/2560893803.py:122: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

              precision    recall  f1-score   support

         FAC       0.00      0.00      0.00         1
         GPE       0.73      0.85      0.79        26
         LOC       0.60      0.60      0.60         5
         ORG       0.00      0.00      0.00         1
         PER       0.90      0.94      0.92       277
         VEH       0.00      0.00      0.00         4

   micro avg       0.88      0.91      0.89       314
   macro avg       0.37      0.40      0.38       314
weighted avg       0.86      0.91      0.89       314

/home/nika/Documents/Code/NER/.venv/lib/python3.10/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

              precision    recall  f1-score   support

         FAC       1.00      1.00      1.00         1
         GPE       0.76      0.85      0.80        26
         LOC       1.00      0.80      0.89         5
         ORG       0.00      0.00      0.00         1
         PER       0.92      0.95      0.93       277
         VEH       0.50      0.25      0.33         4

   micro avg       0.90      0.92      0.91       314
   macro avg       0.70      0.64      0.66       314
weighted avg       0.90      0.92      0.91       314

              precision    recall  f1-score   support

         FAC       1.00      1.00      1.00         1
         GPE       0.82      0.88      0.85        26
         LOC       1.00      0.80      0.89         5
         ORG       1.00      1.00      1.00         1
         PER       0.91      0.96      0.93       277
         VEH       0.33      0.25      0.29         4

   micro avg       0.90      0.94      0.92       314
   macro avg       0.84      0.82      0.83       314
weighted avg       0.90      0.94      0.92       314

              precision    recall  f1-score   support

         FAC       1.00      1.00      1.00         1
         GPE       0.85      0.88      0.87        26
         LOC       1.00      0.80      0.89         5
         ORG       1.00      1.00      1.00         1
         PER       0.92      0.96      0.94       277
         VEH       0.50      0.50      0.50         4

   micro avg       0.91      0.95      0.93       314
   macro avg       0.88      0.86      0.87       314
weighted avg       0.91      0.95      0.93       314

('./rubert-ner/final/tokenizer_config.json',
 './rubert-ner/final/special_tokens_map.json',
 './rubert-ner/final/vocab.txt',
 './rubert-ner/final/added_tokens.json',
 './rubert-ner/final/tokenizer.json')

In [4]:
from transformers import AutoTokenizer, AutoModelForTokenClassification
import torch

# Загрузка токенизатора и модели
tokenizer = AutoTokenizer.from_pretrained("DeepPavlov/rubert-base-cased")
model = AutoModelForTokenClassification.from_pretrained("./rubert-ner/final")  # Укажите путь к вашей модели

# Новый текст для предсказания
new_sentences = [
    "Тимохин и Наташа Ростова молчал, и лицо его так было неприятно, что Пьер обращался более к добродушному батальонному командиру Тимохину, чем к Болконскому.",
    "29-го мая Наполеон выехал из Дрездена, где он пробыл три недели, окруженный двором, составленным из принцев, герцогов, королей и даже одного императора.",
    "Кутузов сидел, понурив седую голову и опустившись тяжелым телом, на покрытой ковром лавке, на том самом месте, на котором утром его видел Пьер. Он не делал никаких распоряжении, а только соглашался или не соглашался на то, что предлагали ему."
]

# Токенизация предложений
inputs = tokenizer(new_sentences, padding=True, truncation=True, return_tensors="pt")

# Получение предсказаний (выход модели)
with torch.no_grad():  # Отключаем вычисление градиентов
    outputs = model(**inputs)
    predictions = outputs.logits

# Получаем индексы наиболее вероятных меток
predicted_labels = torch.argmax(predictions, dim=-1)

# Преобразуем индексы в метки
label_map = model.config.id2label  # Сопоставление индекса метки и её имени
predicted_labels = predicted_labels.cpu().numpy()

# Печатаем результаты
for i, (sentence, label_seq) in enumerate(zip(new_sentences, predicted_labels)):
    # Преобразуем id в токены для текущего предложения
    tokens = tokenizer.convert_ids_to_tokens(inputs['input_ids'][i])
    
    print(f"Предсказания для: {sentence}")
    for token, label in zip(tokens, label_seq):
        if token.startswith("##"):  # Пропускаем субтокены
            continue
        print(f"{token} => {label_map[label]}")
    print()  # Пустая строка между предложениями

Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Предсказания для: Тимохин и Наташа Ростова молчал, и лицо его так было неприятно, что Пьер обращался более к добродушному батальонному командиру Тимохину, чем к Болконскому.
[CLS] => I-PER
Тимо => B-PER
и => O
Наташа => B-PER
Ростова => I-PER
молчал => O
, => O
и => O
лицо => O
его => O
так => O
было => O
неприят => O
, => O
что => O
Пьер => B-PER
обращался => O
более => O
к => O
добродуш => O
батальон => O
командиру => O
Тимо => B-PER
, => O
чем => O
к => O
Бол => B-PER
. => O
[SEP] => I-PER
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => B-PER
[PAD] => B-PER
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => B-PER
[PAD] => I-PER
[PAD] => B-PER
[PAD] => O
[PAD] => B-PER
[PAD] => O

Предсказания для: 29-го мая Наполеон выехал из Дрездена, где он пробыл три недели, окруженный двором, составленным из принцев, герцогов, королей и даже одного императора.
[CLS] => O
29 => O
- => O
го => O
мая => O
Наполеон => B-PER
выехал => O
из => O
Дрездена => B-GPE
, => O
где => O
он => O
пробыл => O
три => O
недели => O
, => O
окруженный => O
двором => O
, => O
составлен => O
из => O
принцев => O
, => O
герцогов => O
, => O
королей => O
и => O
даже => O
одного => O
императора => O
. => O
[SEP] => I-PER
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O
[PAD] => O

Предсказания для: Кутузов сидел, понурив седую голову и опустившись тяжелым телом, на покрытой ковром лавке, на том самом месте, на котором утром его видел Пьер. Он не делал никаких распоряжении, а только соглашался или не соглашался на то, что предлагали ему.
[CLS] => O
Кутузов => B-PER
сидел => O
, => O
пон => O
сед => O
голову => O
и => O
опуст => O
тяжелым => O
телом => O
, => O
на => O
покрытой => O
ков => O
лавке => O
, => O
на => O
том => O
самом => O
месте => O
, => O
на => O
котором => O
утром => O
его => O
видел => O
Пьер => B-PER
. => O
Он => O
не => O
делал => O
никаких => O
распоряжении => O
, => O
а => O
только => O
соглашался => O
или => O
не => O
соглашался => O
на => O
то => O
, => O
что => O
предлагали => O
ему => O
. => O
[SEP] => O

In [2]:
import os
import numpy as np
from pathlib import Path
from transformers import AutoTokenizer, AutoModelForTokenClassification, TrainingArguments, Trainer, DataCollatorForTokenClassification
from datasets import DatasetDict, Dataset
from sklearn.metrics import classification_report, confusion_matrix
from seqeval.metrics import f1_score, classification_report as seqeval_classification_report
import pandas as pd

# === Пути ===
data_dir = Path("rubert.ipynb/datasets")
model_checkpoint = "DeepPavlov/rubert-base-cased"
label_list = ['O', 'B-PER', 'I-PER', 'B-ORG', 'I-ORG', 'B-LOC', 'I-LOC', 'B-GPE', 'I-GPE', 'B-FAC', 'I-FAC', 'B-VEH', 'I-VEH']
label2id = {label: i for i, label in enumerate(label_list)}
id2label = {i: label for label, i in label2id.items()}

# === Загрузка BIO-данных из файлов ===
def load_bio_dataset(data_dir):
    def read_file(file_path):
        tokens = []
        labels = []
        with open(file_path, encoding='utf-8') as f:
            tok_seq = []
            lab_seq = []
            for line in f:
                line = line.strip()
                if not line:
                    if tok_seq:
                        tokens.append(tok_seq)
                        labels.append(lab_seq)
                        tok_seq, lab_seq = [], []
                else:
                    token, label = line.split()
                    tok_seq.append(token)
                    lab_seq.append(label)
        return {"tokens": tokens, "ner_tags": labels}

    return DatasetDict({
        "train": Dataset.from_dict(read_file(data_dir / "train.txt")),
        "validation": Dataset.from_dict(read_file(data_dir / "val.txt")),
        "test": Dataset.from_dict(read_file(data_dir / "test.txt")),
    })

# === Токенизатор ===
tokenizer = AutoTokenizer.from_pretrained(model_checkpoint)

# === Преобразуем строки меток в ID ===
def encode_labels(example):
    tokens = example["tokens"]
    labels = example["ner_tags"]
    tokenized = tokenizer(tokens, is_split_into_words=True, truncation=True)
    word_ids = tokenized.word_ids()
    aligned_labels = []
    previous_word_idx = None
    for word_idx in word_ids:
        if word_idx is None:
            aligned_labels.append(-100)
        elif word_idx != previous_word_idx:
            aligned_labels.append(label2id[labels[word_idx]])
        else:
            # В случае субтокена заменяем B- на I-
            label = labels[word_idx]
            if label.startswith("B-"):
                label = label.replace("B-", "I-")
            aligned_labels.append(label2id[label])
        previous_word_idx = word_idx
    tokenized["labels"] = aligned_labels
    return tokenized

# === Загружаем данные ===
dataset = load_bio_dataset(data_dir)
encoded_dataset = dataset.map(encode_labels, batched=False)

# === Модель ===
model = AutoModelForTokenClassification.from_pretrained(
    model_checkpoint,
    num_labels=len(label_list),
    id2label=id2label,
    label2id=label2id
)

# === Аргументы тренировки ===
training_args = TrainingArguments(
    output_dir="./rubert-ner",
    evaluation_strategy="epoch",
    save_strategy="epoch",
    learning_rate=2e-5,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    num_train_epochs=4,
    weight_decay=0.01,
    save_total_limit=2,
    logging_dir="./logs",
    logging_steps=50,
    load_best_model_at_end=True,
    metric_for_best_model="f1",
    greater_is_better=True,
)

# === Вычисление метрик (с добавлением конфузионной матрицы) ===
def compute_metrics(eval_preds):
    logits, labels = eval_preds
    predictions = np.argmax(logits, axis=-1)

    true_labels = []
    true_predictions = []

    # Собираем список истинных меток и предсказаний на уровне сущностей (для seqeval)
    for pred, lab in zip(predictions, labels):
        cur_labels = []
        cur_preds = []
        for p, l in zip(pred, lab):
            if l != -100:
                cur_labels.append(id2label[l])
                cur_preds.append(id2label[p])
        true_labels.append(cur_labels)
        true_predictions.append(cur_preds)

    # Вычисляем f1-меру с помощью seqeval
    f1 = f1_score(true_labels, true_predictions)
    print("Seqeval Classification Report:")
    print(seqeval_classification_report(true_labels, true_predictions))
    
    # Для конфузионной матрицы вычисляем метрики на уровне токенов:
    flat_true = [label for seq in true_labels for label in seq]
    flat_pred = [pred for seq in true_predictions for pred in seq]
    cm = confusion_matrix(flat_true, flat_pred, labels=label_list)
    cm_df = pd.DataFrame(cm, index=label_list, columns=label_list)
    print("Confusion Matrix:")
    print(cm_df)
    
    return {"f1": f1}

# === Обучение ===
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=encoded_dataset["train"],
    eval_dataset=encoded_dataset["validation"],
    tokenizer=tokenizer,
    data_collator=DataCollatorForTokenClassification(tokenizer),
    compute_metrics=compute_metrics,
)

trainer.train()
trainer.save_model("./rubert-ner/final")
tokenizer.save_pretrained("./rubert-ner/final")

Map:   0%|          | 0/2179 [00:00<?, ? examples/s]Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.
Map: 100%|██████████| 2179/2179 [00:00<00:00, 6665.81 examples/s]
Map: 100%|██████████| 467/467 [00:00<00:00, 6796.08 examples/s]
Map: 100%|██████████| 468/468 [00:00<00:00, 6920.42 examples/s]
Some weights of BertForTokenClassification were not initialized from the model checkpoint at DeepPavlov/rubert-base-cased and are newly initialized: ['classifier.bias', 'classifier.weight']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
/home/nika/Documents/Code/NER/.venv/lib/python3.10/site-packages/transformers/training_args.py:1611: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(
/tmp/ipykernel_9877/1559627396.py:135: FutureWarning: `tokenizer` is deprecated and will be removed in version 5.0.0 for `Trainer.__init__`. Use `processing_class` instead.
  trainer = Trainer(

Seqeval Classification Report:
              precision    recall  f1-score   support

         FAC       0.00      0.00      0.00         1
         GPE       0.69      0.85      0.76        26
         LOC       0.25      0.20      0.22         5
         ORG       0.00      0.00      0.00         1
         PER       0.89      0.92      0.91       277
         VEH       0.00      0.00      0.00         4

   micro avg       0.86      0.89      0.88       314
   macro avg       0.30      0.33      0.31       314
weighted avg       0.85      0.89      0.87       314

Confusion Matrix:
          O  B-PER  I-PER  B-ORG  I-ORG  B-LOC  I-LOC  B-GPE  I-GPE  B-FAC  \
O      9344      6      4      0      0      0      0      1      4      0
B-PER     6    265      6      0      0      0      0      0      0      0
I-PER    13      7    209      0      0      0      0      0      2      0
B-ORG     1      0      0      0      0      0      0      0      0      0
I-ORG     3      0      0      0      0      0      0      0      0      0
B-LOC     0      0      0      0      0      4      0      1      0      0
I-LOC     0      0      0      0      0      0      0      0      3      0
B-GPE     3      1      0      0      0      0      0     22      0      0
I-GPE     0      1      1      0      0      0      0      1     27      0
B-FAC     0      1      0      0      0      0      0      0      0      0
I-FAC     1      1      1      0      0      0      0      0      0      0
B-VEH     1      2      0      0      0      0      0      1      0      0
I-VEH     6      0      5      0      0      0      0      0      1      0

       I-FAC  B-VEH  I-VEH
O          0      0      0
B-PER      0      0      0
I-PER      0      0      0
B-ORG      0      0      0
I-ORG      0      0      0
B-LOC      0      0      0
I-LOC      0      0      0
B-GPE      0      0      0
I-GPE      0      0      0
B-FAC      0      0      0
I-FAC      0      0      0
B-VEH      0      0      0
I-VEH      0      0      0

/home/nika/Documents/Code/NER/.venv/lib/python3.10/site-packages/seqeval/metrics/v1.py:57: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))

Seqeval Classification Report:
              precision    recall  f1-score   support

         FAC       1.00      1.00      1.00         1
         GPE       0.92      0.85      0.88        26
         LOC       1.00      0.80      0.89         5
         ORG       1.00      1.00      1.00         1
         PER       0.93      0.96      0.94       277
         VEH       0.00      0.00      0.00         4

   micro avg       0.93      0.93      0.93       314
   macro avg       0.81      0.77      0.79       314
weighted avg       0.92      0.93      0.93       314

Confusion Matrix:
          O  B-PER  I-PER  B-ORG  I-ORG  B-LOC  I-LOC  B-GPE  I-GPE  B-FAC  \
O      9349      1      3      0      0      0      0      1      5      0
B-PER     5    269      3      0      0      0      0      0      0      0
I-PER     9      5    217      0      0      0      0      0      0      0
B-ORG     0      0      0      0      1      0      0      0      0      0
I-ORG     0      0      0      0      3      0      0      0      0      0
B-LOC     0      0      0      0      0      4      0      1      0      0
I-LOC     0      0      0      0      0      0      3      0      0      0
B-GPE     1      3      0      0      0      0      0     22      0      0
I-GPE     0      1      7      0      0      0      0      0     22      0
B-FAC     0      0      0      0      0      0      0      0      0      1
I-FAC     0      0      0      0      0      0      0      0      0      0
B-VEH     1      3      0      0      0      0      0      0      0      0
I-VEH     3      1      6      0      0      0      0      0      0      0

       I-FAC  B-VEH  I-VEH
O          0      0      0
B-PER      0      0      0
I-PER      0      0      0
B-ORG      0      0      0
I-ORG      0      0      0
B-LOC      0      0      0
I-LOC      0      0      0
B-GPE      0      0      0
I-GPE      0      0      0
B-FAC      0      0      0
I-FAC      3      0      0
B-VEH      0      0      0
I-VEH      0      0      2
Seqeval Classification Report:
              precision    recall  f1-score   support

         FAC       1.00      1.00      1.00         1
         GPE       0.88      0.88      0.88        26
         LOC       1.00      0.80      0.89         5
         ORG       1.00      1.00      1.00         1
         PER       0.94      0.96      0.95       277
         VEH       0.67      0.50      0.57         4

   micro avg       0.93      0.94      0.94       314
   macro avg       0.91      0.86      0.88       314
weighted avg       0.93      0.94      0.94       314

Confusion Matrix:
          O  B-PER  I-PER  B-ORG  I-ORG  B-LOC  I-LOC  B-GPE  I-GPE  B-FAC  \
O      9347      3      3      0      0      0      0      1      5      0
B-PER     4    270      3      0      0      0      0      0      0      0
I-PER     8      6    217      0      0      0      0      0      0      0
B-ORG     0      0      0      1      0      0      0      0      0      0
I-ORG     0      0      0      0      3      0      0      0      0      0
B-LOC     0      0      0      0      0      4      0      1      0      0
I-LOC     0      0      0      0      0      0      3      0      0      0
B-GPE     2      1      0      0      0      0      0     23      0      0
I-GPE     0      1      1      0      0      0      0      0     28      0
B-FAC     0      0      0      0      0      0      0      0      0      1
I-FAC     0      0      0      0      0      0      0      0      0      0
B-VEH     1      1      0      0      0      0      0      0      0      0
I-VEH     3      1      3      0      0      0      0      0      0      0

       I-FAC  B-VEH  I-VEH
O          0      0      0
B-PER      0      0      0
I-PER      0      0      0
B-ORG      0      0      0
I-ORG      0      0      0
B-LOC      0      0      0
I-LOC      0      0      0
B-GPE      0      0      0
I-GPE      0      0      0
B-FAC      0      0      0
I-FAC      3      0      0
B-VEH      0      2      0
I-VEH      0      0      5
Seqeval Classification Report:
              precision    recall  f1-score   support

         FAC       1.00      1.00      1.00         1
         GPE       0.92      0.92      0.92        26
         LOC       1.00      0.80      0.89         5
         ORG       1.00      1.00      1.00         1
         PER       0.94      0.95      0.95       277
         VEH       0.67      0.50      0.57         4

   micro avg       0.94      0.94      0.94       314
   macro avg       0.92      0.86      0.89       314
weighted avg       0.94      0.94      0.94       314

Confusion Matrix:
          O  B-PER  I-PER  B-ORG  I-ORG  B-LOC  I-LOC  B-GPE  I-GPE  B-FAC  \
O      9348      1      4      0      0      0      0      1      5      0
B-PER     5    269      3      0      0      0      0      0      0      0
I-PER     6      7    218      0      0      0      0      0      0      0
B-ORG     0      0      0      1      0      0      0      0      0      0
I-ORG     0      0      0      0      3      0      0      0      0      0
B-LOC     0      0      0      0      0      4      0      1      0      0
I-LOC     0      0      0      0      0      0      3      0      0      0
B-GPE     1      1      0      0      0      0      0     24      0      0
I-GPE     0      1      1      0      0      0      0      0     28      0
B-FAC     0      0      0      0      0      0      0      0      0      1
I-FAC     0      0      0      0      0      0      0      0      0      0
B-VEH     1      1      0      0      0      0      0      0      0      0
I-VEH     3      0      3      0      0      0      0      0      0      0

       I-FAC  B-VEH  I-VEH
O          0      0      0
B-PER      0      0      0
I-PER      0      0      0
B-ORG      0      0      0
I-ORG      0      0      0
B-LOC      0      0      0
I-LOC      0      0      0
B-GPE      0      0      0
I-GPE      0      0      0
B-FAC      0      0      0
I-FAC      3      0      0
B-VEH      0      2      0
I-VEH      0      0      6

('./rubert-ner/final/tokenizer_config.json',
 './rubert-ner/final/special_tokens_map.json',
 './rubert-ner/final/vocab.txt',
 './rubert-ner/final/added_tokens.json',
 './rubert-ner/final/tokenizer.json')

In [7]:
#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
extract_entities.py
~~~~~~~~~~~~~~~~~~~
Извлекает и подсчитывает все сущности из .docx-файла
и сохраняет их в .txt (формат: <текст>\t<тип>\t<частота>).
"""

import torch
from pathlib import Path
from collections import Counter
from itertools import chain
from docx import Document
from transformers import AutoTokenizer, AutoModelForTokenClassification, pipeline

# ---------- Параметры ----------
MODEL_DIR   = Path("rubert-ner/final")                 # каталог сохранённой модели
DOCX_PATH   = Path("texts/Бородино.Чистый текст.docx") # исходный .docx
OUTPUT_PATH = Path("texts/Бородино_entities.txt")      # файл с результатом
MAX_TOKENS  = 490                                      # длина чанка (<512)

# ---------- Загрузка модели ----------
tokenizer = AutoTokenizer.from_pretrained(MODEL_DIR)
model     = AutoModelForTokenClassification.from_pretrained(MODEL_DIR)
model.eval()

device_id = 0 if torch.cuda.is_available() else -1
ner_pipe  = pipeline(
    "ner",
    model=model,
    tokenizer=tokenizer,
    aggregation_strategy="simple",   # объединяем B/I-теги
    device=device_id
)

# ---------- Чтение документа ----------
doc = Document(str(DOCX_PATH))
full_text = "\n".join(p.text for p in doc.paragraphs if p.text.strip())

# ---------- Функция чанкирования ----------
def chunk_text(text: str, max_len: int = MAX_TOKENS):
    """Разбивает текст на чанки ≤max_len токенов."""
    words, cur, chunks, cur_len = text.split(), [], [], 0
    for w in words:
        w_len = len(tokenizer.tokenize(w))
        if cur_len + w_len > max_len:
            chunks.append(" ".join(cur))
            cur, cur_len = [w], w_len
        else:
            cur.append(w)
            cur_len += w_len
    if cur:
        chunks.append(" ".join(cur))
    return chunks

chunks = chunk_text(full_text)
print(f"Чанков к обработке: {len(chunks)}")

# ---------- Извлечение сущностей ----------
batch_size = 16
entities_raw = []
for i in range(0, len(chunks), batch_size):
    batch = chunks[i:i + batch_size]
    batch_out = ner_pipe(batch)          # List[List[Dict]]
    entities_raw.extend(chain.from_iterable(batch_out))

print(f"✓ Сущностей извлечено: {len(entities_raw)}")

# ---------- Подсчёт частот ----------
counter = Counter((ent["word"], ent["entity_group"]) for ent in entities_raw)

# ---------- Запись результата ----------
OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
with OUTPUT_PATH.open("w", encoding="utf-8") as f:
    for (text, ent_type), freq in counter.most_common():
        f.write(f"{text}\t{ent_type}\t{freq}\n")

print(f"Готово! Найдено {len(counter)} уникальных сущностей. "
      f"Результат сохранён в «{OUTPUT_PATH}».")

Device set to use cpu
Asking to truncate to max_length but no maximum length is provided and the model has no predefined maximum length. Default to no truncation.

Чанков к обработке: 76
✓ Сущностей извлечено: 1144
Готово! Найдено 335 уникальных сущностей. Результат сохранён в «texts/Бородино_entities.txt».